[repository]
name = "Hyprspace"
authors = ["KZdkm"]
commit_pins = [
    ["e93fbd7c4f991cb8ef03e433ccc4d43587923e15", "a44d834af279f233a269d065d2e14fe4101d6f41"],
    ["fe7b748eb668136dd0558b7c8279bfcd7ab4d759", "a44d834af279f233a269d065d2e14fe4101d6f41"]
]

[Hyprspace]
description = "Workspace overview"
authors = ["KZdkm"]
output = "build/libHyprspace.so"
build = [
    "meson setup build",
    "ninja -C build"
]
